/*
 * Copyright (C) 2002  Jean-Charles Salzeber <jc@varspool.net>
 *
 * This file is part of penggy.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * $Id$
 *
 */

#if HAVE_CONFIG_H
# include "config.h"
#endif

#if STDC_HEADERS
# include <stdlib.h>
# include <stddef.h>
#else
# if HAVE_STDLIB_H
#  include <stdlib.h>
# endif
#endif

#include "fdo/atoms.h"


const atomdef_t mat_atom_tab[] = {
  {"mat_bool_vertical_scroll"       , MAT_BOOL_VERTICAL_SCROLL       , bool},
  {"mat_bool_disabled"              , MAT_BOOL_DISABLED              , bool},
  {"mat_bool_default"               , MAT_BOOL_DEFAULT               , bool},
  {"mat_bool_resize_vertical"       , MAT_BOOL_RESIZE_VERTICAL       , bool},
  {"mat_bool_resize_horizontal"     , MAT_BOOL_RESIZE_HORIZONTAL     , bool},
  {"mat_bool_modal"                 , MAT_BOOL_MODAL                 , bool},
  {"mat_bool_invisible"             , MAT_BOOL_INVISIBLE             , bool},
  {"mat_bool_hidden"                , MAT_BOOL_HIDDEN                , bool},
  {"mat_orientation"                , MAT_ORIENTATION                , orient},
  {"mat_capacity"                   , MAT_CAPACITY                   , dword},
  {"mat_font_sis"                   , MAT_FONT_SIS                   , multi},
  {"mat_relative_tag"               , MAT_RELATIVE_TAG               , dword},
  {"mat_object_id"                  , MAT_OBJECT_ID                  , gid},
  {"mat_art_id"                     , MAT_ART_ID                     , gid},
  {"mat_width"                      , MAT_WIDTH                      , dword},
  {"mat_height"                     , MAT_HEIGHT                     , dword},
  {"mat_title_pos"                  , MAT_TITLE_POS                  , byte},
  {"mat_ruler"                      , MAT_RULER                      , bytelist},
  {"mat_object_color"               , MAT_OBJECT_COLOR               , bytelist},
  {"mat_vertical_spacing"           , MAT_VERTICAL_SPACING           , dword},
  {"mat_iconify_as"                 , MAT_ICONIFY_AS                 , raw},
  {"mat_plus_group"                 , MAT_PLUS_GROUP                 , raw},
  {"mat_size"                       , MAT_SIZE                       , multi},
  {"mat_title"                      , MAT_TITLE                      , str},
  {"mat_title_width"                , MAT_TITLE_WIDTH                , dword},
  {"mat_bool_list_icons"            , MAT_BOOL_LIST_ICONS            , bool},
  {"mat_bool_graphic_view"          , MAT_BOOL_GRAPHIC_VIEW          , bool},
  {"mat_bool_palette"               , MAT_BOOL_PALETTE               , bool},
  {"mat_bool_horizontal_scroll"     , MAT_BOOL_HORIZONTAL_SCROLL     , bool},
  {"mat_bool_force_scroll"          , MAT_BOOL_FORCE_SCROLL          , bool},
  {"mat_bool_protected_input"       , MAT_BOOL_PROTECTED_INPUT       , bool},
  {"mat_bool_force_no_scroll"       , MAT_BOOL_FORCE_NO_SCROLL       , bool},
  {"mat_bool_non_closeable"         , MAT_BOOL_NON_CLOSEABLE         , bool},
  {"mat_bool_exportable"            , MAT_BOOL_EXPORTABLE            , bool},
  {"mat_bool_importable"            , MAT_BOOL_IMPORTABLE            , bool},
  {"mat_bool_writeable"             , MAT_BOOL_WRITEABLE             , bool},
  {"mat_bool_floating"              , MAT_BOOL_FLOATING              , bool},
  {"mat_bool_contiguous"            , MAT_BOOL_CONTIGUOUS            , bool},
  {"mat_bool_menu"                  , MAT_BOOL_MENU                  , bool},
  {"mat_bool_default_send"          , MAT_BOOL_DEFAULT_SEND          , bool},
  {"mat_bool_double_space"          , MAT_BOOL_DOUBLE_SPACE          , bool},
  {"mat_object_type"                , MAT_OBJECT_TYPE                , objst},
  {"mat_vert_scroll_capacity"       , MAT_VERT_SCROLL_CAPACITY       , dword},
  {"mat_horz_scroll_capacity"       , MAT_HORZ_SCROLL_CAPACITY       , dword},
  {"mat_font_id"                    , MAT_FONT_ID                    , byte},
  {"mat_font_size"                  , MAT_FONT_SIZE                  , dword},
  {"mat_font_style"                 , MAT_FONT_STYLE                 , byte},
  {"mat_value"                      , MAT_VALUE                      , dword},
  {"mat_border"                     , MAT_BORDER                     , raw},
  {"mat_command_key"                , MAT_COMMAND_KEY                , raw},
  {"mat_dirty_query"                , MAT_DIRTY_QUERY                , bool},
  {"mat_managed_by"                 , MAT_MANAGED_BY                 , dword},
  {"mat_validation"                 , MAT_VALIDATION                 , dword},
  {"mat_horizontal_spacing"         , MAT_HORIZONTAL_SPACING         , dword},
  {"mat_style_id"                   , MAT_STYLE_ID                   , gid},
  {"mat_minimum"                    , MAT_MINIMUM                    , dword},
  {"mat_maximum"                    , MAT_MAXIMUM                    , dword},
  {"mat_horz_scroll_value"          , MAT_HORZ_SCROLL_VALUE          , dword},
  {"mat_vert_scroll_value"          , MAT_VERT_SCROLL_VALUE          , dword},
  {"mat_bool_invert"                , MAT_BOOL_INVERT                , bool},
  {"mat_position"                   , MAT_POSITION                   , byte},
  {"mat_log_object"                 , MAT_LOG_OBJECT                 , byte},
  {"mat_paragraph"                  , MAT_PARAGRAPH                  , bool},
  {"mat_scroll_threshold"           , MAT_SCROLL_THRESHOLD           , dword},
  {"mat_shortcut_key"               , MAT_SHORTCUT_KEY               , str},
  {"mat_sort_order"                 , MAT_SORT_ORDER                 , byte},
  {"mat_unfocused"                  , MAT_UNFOCUSED                  , bool},
  {"mat_bool_permanent"             , MAT_BOOL_PERMANENT             , bool},
  {"mat_bool_ignore"                , MAT_BOOL_IGNORE                , bool},
  {"mat_increment"                  , MAT_INCREMENT                  , dword},
  {"mat_bool_no_border"             , MAT_BOOL_NO_BORDER             , bool},
  {"mat_bool_modified"              , MAT_BOOL_MODIFIED              , bool},
  {"mat_link_content_to_rid"        , MAT_LINK_CONTENT_TO_RID        , dword},
  {"mat_bool_precise"               , MAT_BOOL_PRECISE               , bool},
  {"mat_precise_width"              , MAT_PRECISE_WIDTH              , dword},
  {"mat_precise_height"             , MAT_PRECISE_HEIGHT             , dword},
  {"mat_precise_x"                  , MAT_PRECISE_X                  , dword},
  {"mat_precise_y"                  , MAT_PRECISE_Y                  , dword},
  {"mat_color_face"                 , MAT_COLOR_FACE                 , bytelist},
  {"mat_color_text"                 , MAT_COLOR_TEXT                 , bytelist},
  {"mat_color_top_edge"             , MAT_COLOR_TOP_EDGE             , bytelist},
  {"mat_color_bottom_edge"          , MAT_COLOR_BOTTOM_EDGE          , bytelist},
  {"mat_bool_gradual_shadow"        , MAT_BOOL_GRADUAL_SHADOW        , bool},
  {"mat_frame_style"                , MAT_FRAME_STYLE                , word},
  {"mat_trigger_style"              , MAT_TRIGGER_STYLE              , word},
  {"mat_color_selected"             , MAT_COLOR_SELECTED             , bytelist},
  {"mat_color_text_shadow"          , MAT_COLOR_TEXT_SHADOW          , bytelist},
  {"mat_timer_event"                , MAT_TIMER_EVENT                , dword},
  {"mat_timer_duration"             , MAT_TIMER_DURATION             , dword},
  {"mat_bool_background_pic"        , MAT_BOOL_BACKGROUND_PIC        , bool},
  {"mat_bool_background_flood"      , MAT_BOOL_BACKGROUND_FLOOD      , bool},
  {"mat_color_frame_hilight"        , MAT_COLOR_FRAME_HILIGHT        , bytelist},
  {"mat_color_frame_shadow"         , MAT_COLOR_FRAME_SHADOW         , bytelist},
  {"mat_art_frame"                  , MAT_ART_FRAME                  , dword},
  {"mat_art_animation_rate"         , MAT_ART_ANIMATION_RATE         , dword},
  {"mat_art_animation_seq"          , MAT_ART_ANIMATION_SEQ          , bytelist},
  {"mat_bool_repeat_animation"      , MAT_BOOL_REPEAT_ANIMATION      , bool},
  {"mat_bool_background_tile"       , MAT_BOOL_BACKGROUND_TILE       , bool},
  {"mat_context_help"               , MAT_CONTEXT_HELP               , str},
  {"mat_drop_data_type"             , MAT_DROP_DATA_TYPE             , dword},
  {"mat_field_script"               , MAT_FIELD_SCRIPT               , byte},
  {"mat_encode_type"                , MAT_ENCODE_TYPE                , raw},
  {"mat_bool_first_script"          , MAT_BOOL_FIRST_SCRIPT          , bool},
  {"mat_bool_list_allow_entry"      , MAT_BOOL_LIST_ALLOW_ENTRY      , bool},
  {"mat_url"                        , MAT_URL                        , str},
  {"mat_bool_expand_to_fit"         , MAT_BOOL_EXPAND_TO_FIT         , bool},
  {"mat_sink"                       , MAT_SINK                       , str},
  {"mat_bool_sane"                  , MAT_BOOL_SANE                  , bool},
  {"mat_bool_url_sink"              , MAT_BOOL_URL_SINK              , bool},
  {"mat_bool_drop_at_top"           , MAT_BOOL_DROP_AT_TOP           , bool},
  {"mat_form_icon"                  , MAT_FORM_ICON                  , gid},
  {"mat_content_tag"                , MAT_CONTENT_TAG                , str},
  {"mat_bool_language_popup"        , MAT_BOOL_LANGUAGE_POPUP        , bool},
  {"mat_language_sensitive"         , MAT_LANGUAGE_SENSITIVE         , dword},
  {"mat_bool_palette_art"           , MAT_BOOL_PALETTE_ART           , bool},
  {"mat_set_dflt_extract_type"      , MAT_SET_DFLT_EXTRACT_TYPE      , dword},
  {"mat_art_hint_width"             , MAT_ART_HINT_WIDTH             , dword},
  {"mat_art_hint_height"            , MAT_ART_HINT_HEIGHT            , dword},
  {"mat_art_hint_title"             , MAT_ART_HINT_TITLE             , str},
  {"mat_art_hint_placeholder_id"    , MAT_ART_HINT_PLACEHOLDER_ID    , gid},
  {"mat_art_hint_title_x"           , MAT_ART_HINT_TITLE_X           , dword},
  {"mat_bool_tool_group"            , MAT_BOOL_TOOL_GROUP            , bool},
  {"mat_art_hint_title_y"           , MAT_ART_HINT_TITLE_Y           , dword},
  {"mat_art_hint_title_font_size"   , MAT_ART_HINT_TITLE_FONT_SIZE   , dword},
  {"mat_art_hint_title_font_id"     , MAT_ART_HINT_TITLE_FONT_ID     , dword},
  {"mat_art_hint_title_font_style"  , MAT_ART_HINT_TITLE_FONT_STYLE  , dword},
  {"mat_bool_small_icon"            , MAT_BOOL_SMALL_ICON            , bool},
  {"mat_art_hint_select_placeholder", MAT_ART_HINT_SELECT_PLACEHOLDER, dword},
  {"mat_object_index"               , MAT_OBJECT_INDEX               , dword},
  {"mat_bool_encode_unicode"        , MAT_BOOL_ENCODE_UNICODE        , bool},
  {"mat_text_on_picture_pos"        , MAT_TEXT_ON_PICTURE_POS        , byte},
  {"mat_secure_form"                , MAT_SECURE_FORM                , token},
  {"mat_fp_compose_mail"            , MAT_FP_COMPOSE_MAIL            , raw},
  {"mat_fp_send_im"                 , MAT_FP_SEND_IM                 , raw},
  {"mat_fp_save_to_fp"              , MAT_FP_SAVE_TO_FP              , raw},
  {"mat_bool_page_control"          , MAT_BOOL_PAGE_CONTROL          , bool},
  {"mat_bool_spinner"               , MAT_BOOL_SPINNER               , bool},
  {"mat_bool_detached"              , MAT_BOOL_DETACHED              , bool},
  {"mat_bool_customizable"          , MAT_BOOL_CUSTOMIZABLE          , bool},
  {"mat_bool_detachable"            , MAT_BOOL_DETACHABLE            , bool},
  {"mat_bool_dock_horizontal"       , MAT_BOOL_DOCK_HORIZONTAL       , bool},
  {"mat_bool_dock_vertical"         , MAT_BOOL_DOCK_VERTICAL         , bool},
  {"mat_bool_children_removable"    , MAT_BOOL_CHILDREN_REMOVABLE    , bool},
  {"mat_bool_children_movable"      , MAT_BOOL_CHILDREN_MOVABLE      , bool},
  {"mat_bool_child_removable"       , MAT_BOOL_CHILD_REMOVABLE       , bool},
  {"mat_bool_child_movable"         , MAT_BOOL_CHILD_MOVABLE         , bool},
  {"mat_bool_child_line_feed"       , MAT_BOOL_CHILD_LINE_FEED       , bool},
  {"mat_title_append_screen_name"   , MAT_TITLE_APPEND_SCREEN_NAME   , byte},
  {"mat_url_list"                   , MAT_URL_LIST                   , byte},
  {"mat_tab_set_cur_sel"            , MAT_TAB_SET_CUR_SEL            , dword},
  {"mat_tab_get_cur_sel"            , MAT_TAB_GET_CUR_SEL            , raw},
  {"mat_bool_shared_style"          , MAT_BOOL_SHARED_STYLE          , bool},
  {"mat_bool_active_offline"        , MAT_BOOL_ACTIVE_OFFLINE        , bool},
  {"mat_bool_active_online"         , MAT_BOOL_ACTIVE_ONLINE         , bool},
  {"mat_bool_inactive_for_guest"    , MAT_BOOL_INACTIVE_FOR_GUEST    , bool},
  {"mat_bool_dropdown_button"       , MAT_BOOL_DROPDOWN_BUTTON       , bool},
  {"mat_bool_popup_menu"            , MAT_BOOL_POPUP_MENU            , bool},
  {"mat_bool_ignore_url_list"       , MAT_BOOL_IGNORE_URL_LIST       , bool},
  {"mat_popup_relative_id"          , MAT_POPUP_RELATIVE_ID          , dword},
  {"mat_popup_pfc_path"             , MAT_POPUP_PFC_PATH             , str},
  {"mat_bool_draw_focus"            , MAT_BOOL_DRAW_FOCUS            , bool},
  {"mat_url_next"                   , MAT_URL_NEXT                   , str},
  {"mat_url_prev"                   , MAT_URL_PREV                   , str},
  {"mat_url_parent"                 , MAT_URL_PARENT                 , str},
  {"mat_bool_loggable"              , MAT_BOOL_LOGGABLE              , bool},
  {"mat_secure_field"               , MAT_SECURE_FIELD               , dword},
  {"mat_bool_hide_url"              , MAT_BOOL_HIDE_URL              , bool},
  {"mat_bool_auto_closeable"        , MAT_BOOL_AUTO_CLOSEABLE        , bool},
  {"mat_bool_signoff_menu"          , MAT_BOOL_SIGNOFF_MENU          , bool},
  {"mat_bool_ignore_url"            , MAT_BOOL_IGNORE_URL            , bool},
  {"mat_bool_savable_to_pfc"        , MAT_BOOL_SAVABLE_TO_PFC        , bool},
  {"mat_bool_static_url"            , MAT_BOOL_STATIC_URL            , bool},
  {"mat_intl_font_sis"              , MAT_INTL_FONT_SIS              , multi},
  {"mat_navarrow_pos"               , MAT_NAVARROW_POS               , raw},
  {"mat_navarrow_art"               , MAT_NAVARROW_ART               , dword},
  {"mat_navarrow_pos_x"             , MAT_NAVARROW_POS_X             , dword},
  {"mat_navarrow_pos_y"             , MAT_NAVARROW_POS_Y             , dword},
  {"mat_art_seq"                    , MAT_ART_SEQ                    , multi},
  {"mat_sage_context_help"          , MAT_SAGE_CONTEXT_HELP          , str},
  {"mat_auto_complete"              , MAT_AUTO_COMPLETE              , multi},
  {"mat_left_spacing"               , MAT_LEFT_SPACING               , byte},
  {"mat_top_spacing"                , MAT_TOP_SPACING                , byte},
  {"mat_right_spacing"              , MAT_RIGHT_SPACING              , byte},
  {"mat_bottom_spacing"             , MAT_BOTTOM_SPACING             , byte},
  {"mat_spacing"                    , MAT_SPACING                    , byte},
  {"mat_factory_id"                 , MAT_FACTORY_ID                 , gid},
  {"mat_treectrl_set_class"         , MAT_TREECTRL_SET_CLASS         , dword},
  {"mat_title_access"               , MAT_TITLE_ACCESS               , str},
  {"mat_ctrl_attribute"             , MAT_CTRL_ATTRIBUTE             , dword},
  {"mat_title_access_rids"          , MAT_TITLE_ACCESS_RIDS          , multi},
  {"mat_title_access_rid"           , MAT_TITLE_ACCESS_RID           , dword},
  {"mat_thumb_size"                 , MAT_THUMB_SIZE                 , dword},
  {"mat_bool_hide_ticks"            , MAT_BOOL_HIDE_TICKS            , bool},
  {"mat_color_thumb"                , MAT_COLOR_THUMB                , bytelist},
  {"mat_color_channel"              , MAT_COLOR_CHANNEL              , bytelist},
  {"mat_bool_is_slider"             , MAT_BOOL_IS_SLIDER             , bool},
  {"mat_bool_allow_tabbing"         , MAT_BOOL_ALLOW_TABBING         , bool},
  {"mat_bool_default_trigger"       , MAT_BOOL_DEFAULT_TRIGGER       , bool},
  {"mat_use_style_guide"            , MAT_USE_STYLE_GUIDE            , byte},
  {NULL, -1, na}
};
