#!/bin/sh

# This is a sample script for ip-down
# this script is called when pengfork delete the interface
#
# defined variables:
# IFNAME : the interface name where tunneling is done

IFCONFIG=/sbin/ifconfig
ROUTE=/sbin/route

if [ -x $IFCONFIG ]; then
	$IFCONFIG $IFNAME down 
else
	echo "$0: $IFCONFIG not found"
fi

if [ -x $ROUTE ]; then
        $ROUTE del default dev $IFNAME
else
        echo "$0: $ROUTE not found"
fi
		
