#!/bin/sh

# This is a sample script for ip-up
# this script is called when penggy setup the interface
#
# defined variables:
# IFNAME : the interface name where tunneling is done
# ADDRESS : local ip address
# DOMAIN : the given domain name
# DNS : the given DNS ip address

IFCONFIG=/sbin/ifconfig
ROUTE=/sbin/route

if [ -x $IFCONFIG ]; then
	$IFCONFIG $IFNAME $ADDRESS mtu $MTU up
else
	echo "$0: $IFCONFIG not found"
fi

if [ -x $ROUTE ]; then
        $ROUTE add -host $ADDRESS dev $IFNAME
        $ROUTE add default gw $ADDRESS
else
        echo "$0: $ROUTE not found"
fi
		
