#!/bin/sh

export CXXFLAGS="-D_REENTRANT"
	
mv configure configure.tmp
rm configure
cp configure.ori configure
./configure --host i386 --target i386
rm configure
mv configure.tmp configure
make clean

clear
echo "Peng lite 1.0.3 By Guth Stephane (birdy57)"
echo "------------------------------------------"
echo 
if [ $LANG ];
then
	echo "Assuming language: $LANG"
else
	export LANG=eng
	echo "Assuming default language: $LANG"
fi

echo 
echo "In this version you can conditinal compilation making"
echo "(May not compile all drivers that you don't need)"
echo 
echo "Do you want to actived this option ?"
echo "answer by (y or n)"

read Conditionnelle

if [ "$Conditionnelle" = "y" ];
then
	echo "Conditional compilation"
elif [ "$Conditionnelle" = "n" ]; then
	echo "Standart compilation"
else
	echo "Sorry , i don't understand"
	exit 1
fi

if [ "$Conditionnelle" = "y" ];
then
	echo "Do you want to use the modem driver ? (y/n)"
	read Rep
	if [ "$Rep" = "y" ];
	then
		echo "#define WITH_MODEM" >> config.h
	fi

	echo "Do you want to use the Cable driver ? (y/n)"
	read Rep
	if [ "$Rep" = "y" ];
	then
		echo "#define WITH_CABLE" >> config.h
	fi

	echo "Do you want to use the Ppp driver ? (y/n)"
	read Rep
	if [ "$Rep" = "y" ];
	then
		echo "#define WITH_PPP" >> config.h
	fi

	echo "Do you want to use the TunTap driver ? (y/n)"
	read Rep
	if [ "$Rep" = "y" ];
	then
		echo "#define WITH_TUNTAP" >> config.h
	fi

	echo "Do you want to use the Debug ? (y/n)"
	echo "Warning ! that can slow down the connection"
	read Rep
	if [ "$Rep" = "y" ];
	then
		echo "#define WITH_DEBUG" >> config.h
	fi
else
	echo "#define WITH_PPP" >> config.h
	echo "#define WITH_MODEM" >> config.h
	echo "#define WITH_TUNTAP" >> config.h
	echo "#define WITH_CABLE" >> config.h
fi

echo '#define CONFIG_DIR "/etc/Pengaol"' >> config.h

clear	
echo "Please wait while Peng 1.0.1 is compiling -> make.log"
echo " "
echo "Peng's commands (log you as root to use peng)"
echo ""
echo "-a --adduser [login] [password]"
echo "-c --connect [login]"
echo "-d --deluser [login]"
echo "-h --help"
echo "-i --listdriver"
echo "-l --listuser"
echo "-m --makeinit"
echo "-r --restore"
echo "-s --stop"
echo "-v --version"
echo "-x --log"
echo ""
echo "Extra: do a make in XCounter-1.0.6/ and monitoring your bandwith"
echo ""
echo "Configuration files location: /etc/PengAol/"


if make > make.log 2> make.log 
	then
	echo "Compilation, Ok"
	else
	echo "Compilation Error, please consult: make.log"
	exit 1
	fi

# on change les droit de pengaol et on copie

if [ -e "/etc/Pengaol" ];
 	then
	chmod -R 600 /etc/Pengaol 
else
	mkdir /etc/Pengaol
	chmod -R 600 /etc/Pengaol
fi

cd peng
chmod 700 peng

if [ -e "/usr/bin/pengaol" ];
	then
	rm /usr/bin/pengaol
	echo "Delete old Peng Binary, Ok"
fi

echo "pengaol binary: /usr/sbin/peng"
cp peng /usr/sbin/peng
cp ../Doc/PengMessages.txt /etc/Pengaol
cp ../Doc/Dns /etc/Pengaol

peng -m
cd ..

#langue allemande

if echo $LANG | grep -q de 
	then
	echo "recompile has gefunden das sir ein deutch linux utilisieren"
	echo "Wenn sie zum ein deutch aol server verbindet mochten"
	echo "sir mussen am erte das /etc/Pengaol/PengAol.conf editieren"
	echo "und im [CModemDriver] , ServerType=French bei ServerType=German anderen"
	echo " "
	echo "recompile at found german linux"
	echo "If you want to a german aol server connecting"
	echo "You must /etc/Pengaol/PengAol.conf edit"
	echo "and in [CModemDriver] , ServerType=French with ServerType=German change"
	fi

#login password

if peng -l | grep -q "No User" 
	then
	echo "You must at first add one user"
	echo "Please enter your login"
	read Login
	echo "Please enter you password"
	read PassWord
	peng -a "$Login" "$PassWord"
	fi

echo "Installation Success"
echo ""
echo "Have a lot of fun !! "
exit 0
